### ISSUE TITLE
Are you trying to setup OpenVPN server and not a client?

### ISSUE THREAD

**Issue by ranveerkumar** [Trigus42/Private-LAN#1]
I have a WindScribe VPN service account.

Now when you say "Download openvpn configuration" - it gives me only a client configuration. However by following your configuration, it looks like you're trying to setup an OpenVPN server along with Pi-hole!

Your assistance is highly appreciated.

**Comment by Trigus42** [comment]
Yes, you have to download the client configuration from the OpenVPN (or Wireguard) config generator and place it in the corresponding directory (e.g. /etc/openvpn) and start the VPN tunnel. Whether your computer acts as a client or server just depends on the config file.
Is there any unclear or confusing part in particular?

If you want to set up a VPN server you should take a look at [PiVPN](https://github.com/pivpn/pivpn).

**Comment by ranveerkumar** [comment]
Thanks for a real quick answer @Trigus42!
I've downloaded (from: Windscribe)
1. Config file
2. A zip containing: ca.crt, ta.key
![image](https://user-images.githubusercontent.com/5549675/89718964-2fbce900-d9e1-11ea-8d1a-993bf584d13b.png)
I just want pi.hole to redirect all my traffic via WindScribe VPN. Please guide!

**Comment by Trigus42** [comment]
You don't need the zip file with the certificate and key.
You just have to place the file into the directory /etc/openvpn/ and change the file extension to .conf (instead of .ovpn). 

PS: If there is no reason to use OpenVPN I would recommend using Wireguard as you will get better speeds on a device with relatively low performance such as a Raspberry Pi.

**Comment by ranveerkumar** [comment]
I got your point!
Yes I'm not bound to use OpenVPN. I'll try switching to Wireguard. Here's my home infra:
* Pi-hole running on a Raspberry Pi 4 (8GB), within a docker container
* Speed 200mpbs

You're amazing!

**Comment by Trigus42** [comment]
Thanks. Is the issue if it is resolved for you, then?

**Comment by ranveerkumar** [comment]
Just starting on setting up wireguard, and then will follow further steps to hook pi hole with it
Sorry! I don't understand much of the network stuffs.

**Comment by ranveerkumar** [comment]
```sh
systemctl enable wg-quick@wg0
ERROR:systemctl:Unit wg-quick@wg0.service could not be found.
```
```sh
wg-quick up wg0
[#] ip link add wg0 type wireguard
RTNETLINK answers: Operation not permitted
Unable to access interface: Protocol not supported
[#] ip link delete dev wg0
Cannot find device "wg0"
```

**Comment by ranveerkumar** [comment]
```sh
iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
getsockopt failed strangely: Operation not permitted
```

**Comment by ranveerkumar** [comment]
Will it be a good idea to run this whole setup on the host itself and not within a docker container?

**Comment by Trigus42** [comment]
> "service could not be found" | Protocol not supported

Have you installed Wireguard? Is the Wireguard module loaded (in your container)?
Check with ```lsmod | grep wireguard```.
The output should look something like this:
![grafik](https://user-images.githubusercontent.com/59501676/89720063-9553aa00-d9ce-11ea-98a6-114b97216c0d.png)

> Operation not permitted

Are you running all commands as root? Maybe try starting the docker container with the option ```--privileged```?

> Will it be a good idea to run this whole setup on the host itself and not within a docker container?

If it's possible, I would recommend it since I haven't tested it with docker and I also don't have much experience with docker.

**Comment by ranveerkumar** [comment]
Yes docker was running with --privileged.
However, composed it off already and moved to host. And I'm gonna follow everything from scratch. I don't wanna complicate stuffs at this level of traffic. Docker would probably good idea for other applications.

Thank you again!

**Comment by ranveerkumar** [comment]
FYI - the problem was that wireguard module wasn't loaded, and required linux-header update. I followed the solution (end of the page) from here: https://github.com/adrianmihalko/raspberrypiwireguard/issues/11
